### ISSUE TITLE
Automate PR reviewer assignment 

### ISSUE THREAD

**Issue by kei95** [koh1project/apprenticeship_to_master#33]
Let's automate PR reviewer assignment as you will need to assign me manually every time you open a PR which is a bit repetitive and redundant. _**It's always a good idea to automate any of your workflows**_ since the time you will save in the future and the stability provided by the automation are nearly always worth better than the time you spent. I wouldn't give you any clue on what to use to achieve this, so I'd love you to research and set it up yourself as that's what you would need to do in the real-life work environment. Good luck!

**Comment by kei95** [comment]
@koh1project Looks like I can't set this issue in the project. I probably don't have permission to edit it so could you check it out? Thanks

**Comment by koh1project** [comment]
Sorry for that, I think you're right.  I invited you to the project. I will try to figure out how to set automate workflow!

**Comment by koh1project** [comment]
@kei95 I've found candidates from Marketplace and will use either one:

- https://github.com/delivery-much/actions-assigner
- https://github.com/actions-automation/pull-request-responsibility

Please let me know if I am not towards what you expected me in this learning process. If it is not what you meant, using a ready-made tool may be less helpful to learning.
If this method is acceptable, please ignore the above line👍
