### ISSUE TITLE
Set auto formatting on commit with husky

### ISSUE THREAD

**Issue by koh1project** [koh1project/apprenticeship_to_master#45]
Related:
https://github.com/koh1project/apprenticeship_to_master/pull/44#pullrequestreview-1145031352
https://github.com/koh1project/apprenticeship_to_master/pull/44#discussion_r997675551

**Comment by Lada496** [comment]
Hey Kohichi-san let me poke my nose,
I think https://eslint.org/docs/latest/rules/padding-line-between-statements can be one solution.
Set rules as explained and run `eslint --fix` (assuming you need other options as well) during pre-commit process. 
Just like you explained to me, we can add any Unix commands in a .husky file, which means this also should work!

**Comment by koh1project** [comment]
@Lada496 Hi Yuko, thank you for sharing the nice idea!
For this time, I have already applied one library, [eslint-plugin-import](https://www.npmjs.com/package/eslint-plugin-import), and worked it on [this commit](https://github.com/koh1project/apprenticeship_to_master/commit/a239a1b5f68b232adf0c8ea8563fe825a5eaedb3), but your suggestion seems to me a configurable idea and will try to use future requirements! 👍

**Comment by koh1project** [comment]
@Lada496 BTW, [this commit](https://github.com/koh1project/apprenticeship_to_master/commit/a9dcc7c6fa2984e489fe90d8a56f043f9955e20e) is another way to set pre-commit hooks! We literary write script in the file, so we can use variables!
